build:
  image: node:4
  commands:
    - npm install --color --quiet --unsafe-perm > npm-install.log
    - "npm start &"
    - npm run ci --color
clone:
  depth: 10
cache:
  mount:
    - node_modules
    - .git
compose:
  selenium:
    image: selenium/standalone-chrome